spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      keepalive-time: '100000'
      maximum-pull-size: '100'
      minimum-idle: '10'
    username: scott
    url: jdbc:oracle:thin:@localhost:1521:xe
    password: tiger
